### ISSUE TITLE
upgrade dataverse on test

### ISSUE THREAD

**Issue by jt14den** [ucla-data-archive/ucla-dataverse#10]

**Comment by jt14den** [comment]
@jmjamison we should do this soon- 4.10.1 is out and we are now 4 releases behind. Can you do this this coming week?

**Comment by jmjamison** [comment]
[x] upgrade to 4.9.3 
[x] upgrade to 4.9.4 
[x] upgrade to 4.10
[x] upgrade to 4.10.1

**Comment by jmjamison** [comment]
After the upgrade to 4.10 the svg format logos don't display, although png does.  There is an issue: <https://github.com/IQSS/dataverse/issues/2843>

This hasn't been added/fixed yet. Noted in issues (by others). Probably will be fixed eventually.   Till then we are limited to tiff, jpg and png

Height shouldn't be more than 50-70 pixels high.

Also lost the 'for test only' note that had been added next to the logo.

**Comment by jmjamison** [comment]
4.10 to 4.10.1 doesn't seem too drastic so I'll upgrade to that one.

**Comment by jmjamison** [comment]
test.dataverse is up to 4.10.1    Guess now we test it and see if everything works ok
